image:
  file: .Dockerfile
tasks:
  - name: Iniciar Mongo
    before: |
      mkdir -p /workspace/data
      mkdir -p /var/log/mongodb
      mkdir -p ./logs
      mongod -f ./mongodb.conf --replSet rs0 --dbpath /workspace/data --fork --logpath ./logs/mongod.log
      mongo --eval 'rs.initiate()'
  - name: Instalar pacotes fila
    init: cd ./fila-processamento && npm install
  - name: Iniciar Fila
    command: cd ./fila-processamento && npm run serve
ports:
  - port: 27017
    visibility: public
